name: pantera
description: "Pantera (Pantau Nusantara) aplikasi penyedia informasi cuaca dan gempa bumi implementasi public API https://data.bmkg.go.id/"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  introduction_screen: ^3.1.14
  get: ^4.6.6
  shared_preferences: ^2.3.4
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  intl: ^0.20.1
  showcaseview: ^3.0.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  flutter_map_marker_popup: ^7.0.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher.png"

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/ic_launcher.png
    - assets/google_fonts/
    - .env

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/google_fonts/MuseoModerno-SemiBold.ttf
        - asset: assets/google_fonts/MuseoModerno-Regular.ttf

