const Map<String, String> firebaseAuthErrorMessages = {
  "admin-restricted-operation": "Operasi ini dibatasi untuk administrator.",
  "argument-error": "Argumen yang diberikan tidak valid.",
  "app-not-authorized":
      "Aplikasi ini tidak diizinkan untuk menggunakan Firebase.",
  "app-not-installed": "Aplikasi ini tidak terinstal di perangkat Anda.",
  "captcha-check-failed": "Pemeriksaan Google reCAPTCHA gagal.",
  "code-expired": "Kode yang diberikan telah kedaluwarsa.",
  "cordova-not-ready": "Cordova belum siap.",
  "cors-unsupported": "CORS tidak didukung oleh browser Anda.",
  "credential-already-in-use":
      "Kredensial ini sudah terhubung dengan akun lain.",
  "custom-token-mismatch": "Token kustom dan kunci API tidak cocok.",
  "requires-recent-login":
      "Silakan login lagi, karena login terakhir Anda sudah terlalu lama.",
  "dependent-sdk-initialized-before-auth":
      "Harap inisialisasi SDK Firebase Auth sebelum SDK lainnya.",
  "dynamic-link-not-activated": "Tautan dinamis tidak diaktifkan.",
  "email-change-needs-verification": "Harap verifikasi alamat email baru Anda.",
  "email-already-in-use": "Alamat email sudah digunakan.",
  "emulator-config-failed": "Konfigurasi emulator gagal.",
  "expired-action-code": "Kode aksi telah kedaluwarsa.",
  "cancelled-popup-request": "Permintaan popup dibatalkan.",
  "internal-error": "Terjadi kesalahan internal.",
  "invalid-api-key": "Kunci API yang diberikan tidak valid.",
  "invalid-app-credential": "Kredensial aplikasi tidak valid.",
  "invalid-app-id": "ID aplikasi tidak valid.",
  "invalid-user-token": "Token pengguna tidak valid.",
  "invalid-auth-event": "Peristiwa autentikasi tidak valid.",
  "invalid-cert-hash": "Hash sertifikat tidak valid.",
  "invalid-verification-code": "Kode verifikasi yang diberikan tidak valid.",
  "invalid-continue-uri": "URL lanjutan tidak valid.",
  "invalid-cordova-configuration": "Konfigurasi Cordova tidak valid.",
  "invalid-custom-token": "Token kustom tidak valid.",
  "invalid-dynamic-link-domain": "Domain tautan dinamis tidak valid.",
  "invalid-email": "Alamat email tidak valid.",
  "invalid-emulator-scheme": "Skema emulator tidak valid.",
  "invalid-credential":
      "Informasi login tidak valid. Harap periksa kredensial Anda dan coba lagi.",
  "invalid-message-payload": "Beban pesan tidak valid.",
  "invalid-multi-factor-session": "Sesi autentikasi multi-faktor tidak valid.",
  "invalid-oauth-client-id": "ID klien OAuth tidak valid.",
  "invalid-oauth-provider": "Penyedia OAuth tidak valid.",
  "invalid-action-code": "Kode aksi reset password tidak valid.",
  "unauthorized-domain": "Domain tidak sah.",
  "wrong-password": "Kata sandi salah.",
  "invalid-persistence-type": "Jenis persistensi tidak valid.",
  "invalid-phone-number": "Nomor telepon tidak valid.",
  "invalid-provider-id": "ID penyedia tidak valid.",
  "invalid-recipient-email": "Alamat email penerima tidak valid.",
  "invalid-sender": "Pengirim tidak valid.",
  "invalid-verification-id": "ID verifikasi tidak valid.",
  "invalid-tenant-id": "ID penyewa tidak valid.",
  "multi-factor-info-not-found":
      "Informasi autentikasi multi-faktor tidak ditemukan.",
  "multi-factor-auth-required": "Autentikasi multi-faktor diperlukan.",
  "missing-android-pkg-name": "Nama paket Android hilang.",
  "missing-app-credential": "Kredensial aplikasi hilang.",
  "auth-domain-config-required": "Konfigurasi domain autentikasi hilang.",
  "missing-verification-code": "Kode verifikasi hilang.",
  "missing-continue-uri": "URL lanjutan hilang.",
  "missing-iframe-start": "Mulai iframe hilang.",
  "missing-ios-bundle-id": "ID bundel iOS hilang.",
  "missing-or-invalid-nonce": "Nonce hilang atau tidak valid.",
  "missing-multi-factor-info": "Informasi autentikasi multi-faktor hilang.",
  "missing-multi-factor-session": "Sesi autentikasi multi-faktor hilang.",
  "missing-phone-number": "Nomor telepon hilang.",
  "missing-verification-id": "ID verifikasi hilang.",
  "app-deleted": "Modul autentikasi telah dihapus.",
  "account-exists-with-different-credential":
      "Akun dengan email ini sudah ada dengan kredensial yang berbeda.",
  "network-request-failed": "Permintaan jaringan gagal.",
  "null-user": "Tidak ada pengguna yang sedang masuk.",
  "no-auth-event": "Tidak ada peristiwa autentikasi.",
  "no-such-provider": "Penyedia identitas tidak ditemukan.",
  "operation-not-allowed": "Operasi ini tidak diizinkan.",
  "operation-not-supported-in-this-environment":
      "Operasi ini tidak didukung di lingkungan Anda saat ini.",
  "popup-blocked": "Popup diblokir oleh browser.",
  "popup-closed-by-user": "Popup ditutup oleh pengguna.",
  "provider-already-linked": "Penyedia ini sudah terhubung dengan akun Anda.",
  "quota-exceeded": "Kuota terlampaui.",
  "redirect-cancelled-by-user": "Pengalihan dibatalkan oleh pengguna.",
  "redirect-operation-pending": "Operasi pengalihan tertunda.",
  "rejected-credential": "Kredensial ditolak.",
  "second-factor-already-in-use":
      "Metode autentikasi faktor kedua sudah digunakan.",
  "maximum-second-factor-count-exceeded":
      "Jumlah maksimum metode faktor kedua terlampaui.",
  "tenant-id-mismatch": "ID penyewa tidak cocok.",
  "timeout": "Waktu habis.",
  "user-token-expired": "Token pengguna telah kedaluwarsa.",
  "too-many-requests": "Terlalu banyak upaya. Silakan coba lagi nanti.",
  "unauthorized-continue-uri": "URL lanjutan tidak sah.",
  "unsupported-first-factor":
      "Metode autentikasi faktor pertama tidak didukung.",
  "unsupported-persistence-type": "Jenis persistensi tidak didukung.",
  "unsupported-tenant-operation": "Operasi penyewa tidak didukung.",
  "unverified-email": "Alamat email belum diverifikasi.",
  "user-cancelled": "Pengguna membatalkan autentikasi.",
  "user-not-found": "Pengguna tidak ditemukan.",
  "user-disabled": "Akun pengguna dinonaktifkan.",
  "user-mismatch": "Ketidaksesuaian pengguna.",
  "user-signed-out": "Pengguna telah keluar.",
  "weak-password": "Kata sandi terlalu lemah.",
  "web-storage-unsupported":
      "Penyimpanan web tidak didukung oleh browser Anda.",
  "already-initialized": "Firebase Auth sudah diinisialisasi.",
  "recaptcha-not-enabled": "Google reCAPTCHA belum diaktifkan.",
  "missing-recaptcha-token": "Token Google reCAPTCHA hilang.",
  "invalid-recaptcha-token": "Token Google reCAPTCHA tidak valid.",
  "invalid-recaptcha-action": "Aksi Google reCAPTCHA tidak valid.",
  "missing-client-type": "Tipe klien hilang.",
  "missing-recaptcha-version": "Versi Google reCAPTCHA hilang.",
  "invalid-recaptcha-version": "Versi Google reCAPTCHA tidak valid.",
  "invalid-req-type": "Tipe permintaan tidak valid."
};
